AWSTemplateFormatVersion: '2010-09-09' # テンプレートバージョン情報
Description: Hands-on EC2-Bastion template # テンプレートの説明文
Metadata:
  AWS::CloudFormation::Interface: # Parametersセクションの表示順序を定義
    ParameterGroups:
      - 
        Label1:
          default: General Configuration
        Parameters:
          - NetworkStackName
          - EnvironmentName
      - 
        Label2:
          default: BastionEC2 Configuration
        Parameters:
          - MyGlobalIp
          - BastionKayName
          - ImageId
          - InstanceType
          - VolumeType
          - VolumeSize
Parameters:
  NetworkStackName: # クロススタック参照元のスタック名を入力
    Type: String
    Default: Hands-on-Network

  EnvironmentName:
    Type: String
    Default: Hands-on

  MyGlobalIp: # SSHクライアントがある環境のグローバルIPアドレスを入力
    Type: String

  BastionKayName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: Hands-on-Bastion-Key

  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-04e0b6d6cfa432943 # Amazon Linux 2のAMI ID
    # Default: ami-0ab3794db9457b60a # Amazon Linux 2023のAMI ID
    # Default: ami-0b193da66bc27147b # Amazon Linux 2023のAMI ID

  InstanceType:
    Type: String
    Default: t2.micro

  VolumeType:
    Type: String
    Default: gp3

  VolumeSize:
    Type: Number
    Default: 8

Resources:
########## SG ##########
  BastionSecurityGroup: # 踏み台サーバ用のSGを作成
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPC"
      GroupName: !Sub ${EnvironmentName}-sg-Bastion
      GroupDescription: "SecurityGroup for Bastion"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref MyGlobalIp
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-EC2-Bastion

  BastionToEC2SecurityGroup: # 踏み台サーバからのSSH接続を許可するSGを作成
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPC"
      GroupName: !Sub ${EnvironmentName}-sg-EC2-from-Bastion
      GroupDescription: "SecurityGroup for SSH to EC2 from Bastion"
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref BastionSecurityGroup
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-sg-EC2-from-Bastion

########## EC2 ##########
  Ec2Bastion: # 踏み台サーバ用のEC2を起動
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnet"
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      ImageId: !Ref ImageId
      KeyName: !Ref BastionKayName
      DisableApiTermination: false # 終了保護を無効化
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true # EC2終了時にEBSを削除
            VolumeType: !Ref VolumeType
            VolumeSize: !Ref VolumeSize
      UserData: # EC2起動時にシェルスクリプトを実行(SSHの受け側ポート番号を22から443に変更し、sshdを再起動)
        Fn::Base64: |
          #!/bin/bash
          sed -i .old -e 's/#Port 22/Port 443/g' /etc/ssh/sshd_config
          systemctl restart sshd
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-EC2-Bastion
