AWSTemplateFormatVersion: '2010-09-09' # テンプレートバージョン情報
Description: Hands-on EC2-private template # テンプレートの説明文
Metadata:
  AWS::CloudFormation::Interface: # Parametersセクションの表示順序を定義
    ParameterGroups:
      - 
        Label1:
          default: General Configuration
        Parameters:
          - NetworkStackName
          - EnvironmentName
      - 
        Label2:
          default: EC2 Configuration
        Parameters:
          - EC2Name
          - KeyName
          - ImageId
          - InstanceType
          - VolumeType
          - VolumeSize
Parameters: # スタック作成または更新時にカスタム値を入力
  NetworkStackName: # クロススタック参照元のスタック名を入力
    Type: String
    Default: Hands-on-Network

  EnvironmentName:
    Type: String
    Default: Hands-on

  EC2Name:
    Type: String
    Default: Hands-on-EC2-pri

  KeyName: # 使用するKeypairを選択
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: Hands-on-Key

  ImageId:
    Type: "AWS::EC2::Image::Id"
    Default: ami-04e0b6d6cfa432943 # Amazon Linux 2のAMI ID

  InstanceType:
    Type: String
    Default: t2.micro

  VolumeType:
    Type: String
    Default: gp3

  VolumeSize:
    Type: Number
    Default: 8
Resources:
########## EC2 ##########
  Ec2Instance: # EC2を起動
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PrivateSubnet"
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-NoIngressSecurityGroup"
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      DisableApiTermination: false # 終了保護を無効化
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true # EC2終了時にEBSを削除
            VolumeType: !Ref VolumeType
            VolumeSize: !Ref VolumeSize
      Tags:
        - Key: Name
          Value: !Ref EC2Name